---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ownerhelmrelease3
  namespace: owner
spec:
  chart:
    spec:
      chart: ./ownerapp
      interval: 1m0s
      sourceRef:
        kind: GitRepository
        name: ownerhelmrepo3
        namespace: owner
      version: 1.0.0
  install:
    remediation:
      retries: 3
  interval: 5m0s
  releaseName: ownerhelmrelease3
  targetNamespace: owner2
  timeout: 2m0s
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  values:
    image:
      repository: nginx
      pullPolicy: IfNotPresent
      tag: "1.19"
    nameOverride: ""
    fullnameOverride: ""
    replicaCount: 1
    serviceAccount:
      create: true
      annotations: {}
      name: ""
    service:
      type: ClusterIP
      port: 80
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ownerhelmrepo3
  namespace: owner
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/fk-gitops/helm-repo
