---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ownerhelmrelease1
  namespace: owner
spec:
  chart:
    spec:
      chart: ./nginxapp2
      interval: 60m0s
      sourceRef:
        kind: GitRepository
        name: ownerhelmrepo
        namespace: owner
      version: 1.0.33
  install:
    remediation:
      retries: 3
  interval: 60m0s
  releaseName: ownerhelmrelease1
  targetNamespace: owner
  timeout: 60m0s
  upgrade:
    remediation:
      retries: 2
  test:
    enable: true
  values:
    image:
      repository: nginx
      pullPolicy: IfNotPresent
      tag: "1.27"
    nameOverride: ""
    fullnameOverride: ""
    replicaCount: 2
    serviceAccount:
      create: true
      annotations: {}
      name: ""
    service:
      type: ClusterIP
      port: 80
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ownerhelmrepo
  namespace: owner
spec:
  interval: 60m0s
  ref:
    tag: 1.0.33
  url: https://github.com/fk-gitops/helm-repo
