---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ownerhelmreleasejob
  namespace: owner
spec:
  chart:
    spec:
      chart: ./job1
      interval: 1m0s
      sourceRef:
        kind: GitRepository
        name: ownerhelmrepojob
        namespace: owner
      version: 1.0.19
  install:
    remediation:
      retries: 3
  interval: 2m0s
  releaseName: ownerhelmreleasejob
  targetNamespace: owner
  timeout: 1m0s
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  values:
    image:
      repository: nginx
      pullPolicy: IfNotPresent
      tag: "1.18"
    nameOverride: ""
    fullnameOverride: ""
    replicaCount: 1
    serviceAccount:
      create: true
      annotations: {}
      name: ""
    service:
      type: ClusterIP
      port: 80
